language: generic
install:
- source ./texlive/texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_script: cd $TRAVIS_BUILD_DIR/
script:
- texliveonfly CV.tex
- lualatex CV.tex
deploy:
  provider: releases
  api_key:
    secure: ph3QyTmmawdAK3QjrrthJAxQjw5xNOumz5z58riPIkffI+JgMWshvPS8OkKF9CQ0yn5yEDkoHwErLpXLBC0FP68PtHLOC0c/OEcLctlNz78lcTnokv23tDoMu8JNpElwW+FXFH/MqCwvOUKAjpVgPn7WYl3Hdp1HvTbQCvB/xJY0XaIvuDR8vJvNqBYDfRPb5TTyAeN8TOkrMVrFYZ/eLOXn5ksydmr2Jyzyq2I6l6hEvctGKJwdlEUYsfE0rTNdlLyOqaKf32zskyjz84V4oFwXimyXVfwHdTddxtM4jQLtPhjHe8j7RPtckWUjCXsrP0O4PIwUb6NTpvr/MbWy/ihdo9llfAfHWA4jaLhPRfXeEWB1EBZwn16UICdR2GVnVbIBdcEXzXmsuiwzxz5+RBLxtkMWpzFSkXRalv5KZ0qgV632S5SINUMnPsQhaGQdp+MULA5ecPLa+Y5ZziXiWNJTLzJtpYCfqdDS685HdOAAeVWg8dDYYC1toig+g6Uu7b1L361y4zMJcaFYR7eYRC9aaPIxyiq9iKlIjbqSfb2J5ItbKHWOz4KrVfwPD/DQzFJYIOtan2Jvk1nGok3LiVAKWGdmFvWMuhesQBHQDwNEU/YO1cCSDtixkbchTvYBN80RBT3vvdBf51nDY/aaKof6v8+JdSuy3gybiOel1WY=
  file: CV.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: TomBrien/CV
